# coding: utf-8

"""
    Bangumi API

    你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 

    The version of the OpenAPI document: 2025-11-22
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.v0_subject_relation import V0SubjectRelation

class TestV0SubjectRelation(unittest.TestCase):
    """V0SubjectRelation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V0SubjectRelation:
        """Test V0SubjectRelation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V0SubjectRelation`
        """
        model = V0SubjectRelation()
        if include_optional:
            return V0SubjectRelation(
                id = 56,
                type = 56,
                name = '',
                name_cn = '',
                images = openapi_client.models.images.Images(
                    large = '', 
                    common = '', 
                    medium = '', 
                    small = '', 
                    grid = '', ),
                relation = ''
            )
        else:
            return V0SubjectRelation(
                id = 56,
                type = 56,
                name = '',
                name_cn = '',
                relation = '',
        )
        """

    def testV0SubjectRelation(self):
        """Test V0SubjectRelation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
