# coding: utf-8

"""
    Bangumi API

    你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 

    The version of the OpenAPI document: 2025-11-22
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.user_subject_collection import UserSubjectCollection

class TestUserSubjectCollection(unittest.TestCase):
    """UserSubjectCollection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserSubjectCollection:
        """Test UserSubjectCollection
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserSubjectCollection`
        """
        model = UserSubjectCollection()
        if include_optional:
            return UserSubjectCollection(
                subject_id = 8,
                subject_type = 2,
                rate = 4,
                type = 3,
                comment = '看看',
                tags = ["柯南","万年小学生","推理","青山刚昌","TV"],
                ep_status = 5,
                vol_status = 0,
                updated_at = '2022-06-19T18:44:13.614012700+08:00',
                private = True,
                subject = openapi_client.models.slim_subject.SlimSubject(
                    id = 56, 
                    type = 56, 
                    name = '', 
                    name_cn = '', 
                    short_summary = '', 
                    date = '', 
                    images = openapi_client.models.images.Images(
                        large = '', 
                        common = '', 
                        medium = '', 
                        small = '', 
                        grid = '', ), 
                    volumes = 56, 
                    eps = 56, 
                    collection_total = 56, 
                    score = 1.337, 
                    rank = 56, 
                    tags = null, )
            )
        else:
            return UserSubjectCollection(
                subject_id = 8,
                subject_type = 2,
                rate = 4,
                type = 3,
                tags = ["柯南","万年小学生","推理","青山刚昌","TV"],
                ep_status = 5,
                vol_status = 0,
                updated_at = '2022-06-19T18:44:13.614012700+08:00',
                private = True,
        )
        """

    def testUserSubjectCollection(self):
        """Test UserSubjectCollection"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
