# coding: utf-8

"""
    Bangumi API

    你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 

    The version of the OpenAPI document: 2025-11-22
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.subject import Subject

class TestSubject(unittest.TestCase):
    """Subject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Subject:
        """Test Subject
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Subject`
        """
        model = Subject()
        if include_optional:
            return Subject(
                id = 56,
                type = 2,
                name = '',
                name_cn = '',
                summary = '',
                series = True,
                nsfw = True,
                locked = True,
                var_date = '',
                platform = '',
                images = openapi_client.models.images.Images(
                    large = '', 
                    common = '', 
                    medium = '', 
                    small = '', 
                    grid = '', ),
                infobox = [{"key":"简体中文名","value":"鲁路修·兰佩路基"},{"key":"别名","value":[{"v":"L.L."},{"v":"勒鲁什"},{"v":"鲁鲁修"},{"v":"ゼロ"},{"v":"Zero"},{"k":"英文名","v":"Lelouch Lamperouge"},{"k":"第二中文名","v":"鲁路修·冯·布里塔尼亚"},{"k":"英文名二","v":"Lelouch Vie Britannia"},{"k":"日文名","v":"ルルーシュ・ヴィ・ブリタニア"}]},{"key":"性别","value":"男"},{"key":"生日","value":"12月5日"},{"key":"血型","value":"A型"},{"key":"身高","value":"178cm→181cm"},{"key":"体重","value":"54kg"},{"key":"引用来源","value":"Wikipedia"}],
                volumes = 56,
                eps = 56,
                total_episodes = 56,
                rating = openapi_client.models.rating.Rating(
                    rank = 56, 
                    total = 56, 
                    count = openapi_client.models.count.Count(
                        1 = 56, 
                        2 = 56, 
                        3 = 56, 
                        4 = 56, 
                        5 = 56, 
                        6 = 56, 
                        7 = 56, 
                        8 = 56, 
                        9 = 56, 
                        10 = 56, ), 
                    score = 1.337, ),
                collection = openapi_client.models.collection.Collection(
                    wish = 56, 
                    collect = 56, 
                    doing = 56, 
                    on_hold = 56, 
                    dropped = 56, ),
                meta_tags = [
                    ''
                    ],
                tags = [
                    openapi_client.models.tag.Tag(
                        name = '', 
                        count = 56, )
                    ]
            )
        else:
            return Subject(
                id = 56,
                type = 2,
                name = '',
                name_cn = '',
                summary = '',
                series = True,
                nsfw = True,
                locked = True,
                platform = '',
                images = openapi_client.models.images.Images(
                    large = '', 
                    common = '', 
                    medium = '', 
                    small = '', 
                    grid = '', ),
                volumes = 56,
                eps = 56,
                total_episodes = 56,
                rating = openapi_client.models.rating.Rating(
                    rank = 56, 
                    total = 56, 
                    count = openapi_client.models.count.Count(
                        1 = 56, 
                        2 = 56, 
                        3 = 56, 
                        4 = 56, 
                        5 = 56, 
                        6 = 56, 
                        7 = 56, 
                        8 = 56, 
                        9 = 56, 
                        10 = 56, ), 
                    score = 1.337, ),
                collection = openapi_client.models.collection.Collection(
                    wish = 56, 
                    collect = 56, 
                    doing = 56, 
                    on_hold = 56, 
                    dropped = 56, ),
                meta_tags = [
                    ''
                    ],
                tags = [
                    openapi_client.models.tag.Tag(
                        name = '', 
                        count = 56, )
                    ],
        )
        """

    def testSubject(self):
        """Test Subject"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
