# coding: utf-8

"""
    Bangumi API

    你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 

    The version of the OpenAPI document: 2025-11-22
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.person_detail import PersonDetail

class TestPersonDetail(unittest.TestCase):
    """PersonDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PersonDetail:
        """Test PersonDetail
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PersonDetail`
        """
        model = PersonDetail()
        if include_optional:
            return PersonDetail(
                id = 56,
                name = '',
                type = 1,
                career = [
                    'producer'
                    ],
                images = openapi_client.models.person_images.PersonImages(
                    large = '', 
                    medium = '', 
                    small = '', 
                    grid = '', ),
                summary = '',
                locked = True,
                last_modified = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                infobox = [
                    None
                    ],
                gender = '',
                blood_type = 1,
                birth_year = 56,
                birth_mon = 56,
                birth_day = 56,
                stat = openapi_client.models.stat.Stat(
                    comments = 56, 
                    collects = 56, )
            )
        else:
            return PersonDetail(
                id = 56,
                name = '',
                type = 1,
                career = [
                    'producer'
                    ],
                summary = '',
                locked = True,
                last_modified = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                stat = openapi_client.models.stat.Stat(
                    comments = 56, 
                    collects = 56, ),
        )
        """

    def testPersonDetail(self):
        """Test PersonDetail"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
