# coding: utf-8

"""
    Bangumi API

    你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 

    The version of the OpenAPI document: 2025-11-22
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.legacy_user import LegacyUser

class TestLegacyUser(unittest.TestCase):
    """LegacyUser unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LegacyUser:
        """Test LegacyUser
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LegacyUser`
        """
        model = LegacyUser()
        if include_optional:
            return LegacyUser(
                id = 1,
                url = 'https://bgm.tv/user/sai',
                username = 'sai',
                nickname = 'Sai',
                avatar = openapi_client.models.legacy_user_avatar.Legacy_User_avatar(
                    large = 'https://lain.bgm.tv/pic/user/l/000/00/00/1.jpg?r=1391790456', 
                    medium = 'https://lain.bgm.tv/pic/user/m/000/00/00/1.jpg?r=1391790456', 
                    small = 'https://lain.bgm.tv/pic/user/s/000/00/00/1.jpg?r=1391790456', ),
                sign = 'Awesome!',
                usergroup = 11
            )
        else:
            return LegacyUser(
        )
        """

    def testLegacyUser(self):
        """Test LegacyUser"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
