# coding: utf-8

"""
    Bangumi API

    你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 

    The version of the OpenAPI document: 2025-11-22
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.legacy_mono_base import LegacyMonoBase

class TestLegacyMonoBase(unittest.TestCase):
    """LegacyMonoBase unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LegacyMonoBase:
        """Test LegacyMonoBase
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LegacyMonoBase`
        """
        model = LegacyMonoBase()
        if include_optional:
            return LegacyMonoBase(
                id = 56,
                url = '',
                name = '',
                images = openapi_client.models.legacy_mono_base_images.Legacy_MonoBase_images(
                    large = 'https://lain.bgm.tv/pic/crt/l/ce/65/32_crt_XMJOj.jpg', 
                    medium = 'https://lain.bgm.tv/pic/crt/m/ce/65/32_crt_XMJOj.jpg', 
                    small = 'https://lain.bgm.tv/pic/crt/s/ce/65/32_crt_XMJOj.jpg', 
                    grid = 'https://lain.bgm.tv/pic/crt/g/ce/65/32_crt_XMJOj.jpg', )
            )
        else:
            return LegacyMonoBase(
        )
        """

    def testLegacyMonoBase(self):
        """Test LegacyMonoBase"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
