# coding: utf-8

"""
    Bangumi API

    你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 

    The version of the OpenAPI document: 2025-11-22
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.get_calendar200_response_inner_weekday import GetCalendar200ResponseInnerWeekday

class TestGetCalendar200ResponseInnerWeekday(unittest.TestCase):
    """GetCalendar200ResponseInnerWeekday unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetCalendar200ResponseInnerWeekday:
        """Test GetCalendar200ResponseInnerWeekday
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetCalendar200ResponseInnerWeekday`
        """
        model = GetCalendar200ResponseInnerWeekday()
        if include_optional:
            return GetCalendar200ResponseInnerWeekday(
                en = 'Mon',
                cn = '星期一',
                ja = '月耀日',
                id = 1
            )
        else:
            return GetCalendar200ResponseInnerWeekday(
        )
        """

    def testGetCalendar200ResponseInnerWeekday(self):
        """Test GetCalendar200ResponseInnerWeekday"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
