# coding: utf-8

"""
    Bangumi API

    你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 

    The version of the OpenAPI document: 2025-11-22
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import pprint
import unittest

import openapi_client
from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_add_subject_to_index_by_index_id(self) -> None:
        """Test case for add_subject_to_index_by_index_id

        Add a subject to Index
        """
        pass

    def test_collect_character_by_character_id_and_user_id(self) -> None:
        """Test case for collect_character_by_character_id_and_user_id

        Collect character for current user
        """
        pass

    def test_collect_index_by_index_id_and_user_id(self) -> None:
        """Test case for collect_index_by_index_id_and_user_id

        Collect index for current user
        """
        pass

    def test_collect_person_by_person_id_and_user_id(self) -> None:
        """Test case for collect_person_by_person_id_and_user_id

        Collect person for current user
        """
        pass

    def test_delelte_subject_from_index_by_index_id_and_subject_id(self) -> None:
        """Test case for delelte_subject_from_index_by_index_id_and_subject_id

        Delete a subject from a Index
        """
        pass

    def test_edit_index_by_id(self) -> None:
        """Test case for edit_index_by_id

        Edit index's information
        """
        pass

    def test_edit_index_subjects_by_index_id_and_subject_id(self) -> None:
        """Test case for edit_index_subjects_by_index_id_and_subject_id

        Edit subject information in a index
        """
        pass

    def test_get_calendar(self) -> None:
        """Test case for get_calendar

        每日放送
        """
        pass

    def test_get_character_by_id(self) -> None:
        """Test case for get_character_by_id

        Get Character Detail
        """
        pass

    def test_get_character_image_by_id(self) -> None:
        """Test case for get_character_image_by_id

        Get Character Image
        """
        pass

    def test_get_character_revision_by_revision_id(self) -> None:
        """Test case for get_character_revision_by_revision_id

        Get Character Revision
        """
        pass

    def test_get_character_revisions(self) -> None:
        """Test case for get_character_revisions

        Get Character Revisions
        """
        pass

    def test_get_episode_by_id(self) -> None:
        """Test case for get_episode_by_id

        Get Episode
        """
        pass

    def test_get_episode_revision_by_revision_id(self) -> None:
        """Test case for get_episode_revision_by_revision_id

        Get Episode Revision
        """
        pass

    def test_get_episode_revisions(self) -> None:
        """Test case for get_episode_revisions

        Get Episode Revisions
        """
        pass

    def test_get_episodes(self) -> None:
        """Test case for get_episodes

        Get Episodes
        """
        pass

    def test_get_index_by_id(self) -> None:
        """Test case for get_index_by_id

        Get Index By ID
        """
        pass

    def test_get_index_subjects_by_index_id(self) -> None:
        """Test case for get_index_subjects_by_index_id

        Get Index Subjects
        """
        pass

    def test_get_myself(self) -> None:
        """Test case for get_myself

        Get User
        """
        pass

    def test_get_person_by_id(self) -> None:
        """Test case for get_person_by_id

        Get Person
        """
        pass

    def test_get_person_image_by_id(self) -> None:
        """Test case for get_person_image_by_id

        Get Person Image
        """
        pass

    def test_get_person_revision_by_revision_id(self) -> None:
        """Test case for get_person_revision_by_revision_id

        Get Person Revision
        """
        pass

    def test_get_person_revisions(self) -> None:
        """Test case for get_person_revisions

        Get Person Revisions
        """
        pass

    def test_get_related_characters_by_person_id(self) -> None:
        """Test case for get_related_characters_by_person_id

        get person related characters
        """
        pass

    def test_get_related_characters_by_subject_id(self) -> None:
        """Test case for get_related_characters_by_subject_id

        Get Subject Characters
        """
        pass

    def test_get_related_persons_by_character_id(self) -> None:
        """Test case for get_related_persons_by_character_id

        get character related persons
        """
        pass

    def test_get_related_persons_by_subject_id(self) -> None:
        """Test case for get_related_persons_by_subject_id

        Get Subject Persons
        """
        pass

    def test_get_related_subjects_by_character_id(self) -> None:
        """Test case for get_related_subjects_by_character_id

        get character related subjects
        """
        pass

    def test_get_related_subjects_by_person_id(self) -> None:
        """Test case for get_related_subjects_by_person_id

        get person related subjects
        """
        pass

    def test_get_related_subjects_by_subject_id(self) -> None:
        """Test case for get_related_subjects_by_subject_id

        Get Subject Relations
        """
        pass

    def test_get_subject_by_id(self) -> None:
        """Test case for get_subject_by_id

        获取条目
        """
        pass

    def test_get_subject_image_by_id(self) -> None:
        """Test case for get_subject_image_by_id

        Get Subject Image
        """
        pass

    def test_get_subject_revision_by_revision_id(self) -> None:
        """Test case for get_subject_revision_by_revision_id

        Get Subject Revision
        """
        pass

    def test_get_subject_revisions(self) -> None:
        """Test case for get_subject_revisions

        Get Subject Revisions
        """
        pass

    def test_get_subjects(self) -> None:
        """Test case for get_subjects

        浏览条目
        """
        pass

    def test_get_user_avatar_by_name(self) -> None:
        """Test case for get_user_avatar_by_name

        Get User Avatar by name
        """
        pass

    def test_get_user_by_name(self) -> None:
        """Test case for get_user_by_name

        Get User by name
        """
        pass

    def test_get_user_character_collection(self) -> None:
        """Test case for get_user_character_collection

        获取用户单个角色收藏信息
        """
        pass

    def test_get_user_character_collections(self) -> None:
        """Test case for get_user_character_collections

        获取用户角色收藏列表
        """
        pass

    def test_get_user_collection(self) -> None:
        """Test case for get_user_collection

        获取用户单个条目收藏
        """
        pass

    def test_get_user_collections_by_username(self) -> None:
        """Test case for get_user_collections_by_username

        获取用户收藏
        """
        pass

    def test_get_user_episode_collection(self) -> None:
        """Test case for get_user_episode_collection

        章节收藏信息
        """
        pass

    def test_get_user_person_collection(self) -> None:
        """Test case for get_user_person_collection

        获取用户单个人物收藏信息
        """
        pass

    def test_get_user_person_collections(self) -> None:
        """Test case for get_user_person_collections

        获取用户人物收藏列表
        """
        pass

    def test_get_user_subject_episode_collection(self) -> None:
        """Test case for get_user_subject_episode_collection

        章节收藏信息
        """
        pass

    def test_new_index(self) -> None:
        """Test case for new_index

        Create a new index
        """
        pass

    def test_patch_user_collection(self) -> None:
        """Test case for patch_user_collection

        修改用户单个收藏
        """
        pass

    def test_patch_user_subject_episode_collection(self) -> None:
        """Test case for patch_user_subject_episode_collection

        章节收藏信息
        """
        pass

    def test_post_user_collection(self) -> None:
        """Test case for post_user_collection

        新增或修改用户单个条目收藏
        """
        pass

    def test_put_user_episode_collection(self) -> None:
        """Test case for put_user_episode_collection

        更新章节收藏信息
        """
        pass

    def test_search_characters(self) -> None:
        """Test case for search_characters

        角色搜索
        """
        pass

    def test_search_persons(self) -> None:
        """Test case for search_persons

        人物搜索
        """
        pass

    def test_search_subjects(self) -> None:
        """Test case for search_subjects

        条目搜索
        """
        # Defining the host is optional and defaults to https://api.bgm.tv
        # See configuration.py for a list of all supported configuration parameters.
        configuration = openapi_client.Configuration(
            host = "https://api.bgm.tv"
        )


        # Enter a context with an instance of the API client
        # with openapi_client.ApiClient(configuration) as api_client:
        #     # Create an instance of the API class
        #     api_instance = openapi_client.DefaultApi(api_client)
        #     limit = 1 # int | 分页参数 (optional)
        #     offset = 20 # int | 分页参数 (optional)
        #     search_subjects_request = openapi_client.SearchSubjectsRequest(keyword="日常") # SearchSubjectsRequest |  (optional)
        #     api_response = api_instance.search_subjects(limit=limit, offset=offset, search_subjects_request=search_subjects_request)
        #     print("The response of DefaultApi->search_subjects:\n")
        #     print(api_response)

        pass

    def test_uncollect_character_by_character_id_and_user_id(self) -> None:
        """Test case for uncollect_character_by_character_id_and_user_id

        Uncollect character for current user
        """
        pass

    def test_uncollect_index_by_index_id_and_user_id(self) -> None:
        """Test case for uncollect_index_by_index_id_and_user_id

        Uncollect index for current user
        """
        pass

    def test_uncollect_person_by_person_id_and_user_id(self) -> None:
        """Test case for uncollect_person_by_person_id_and_user_id

        Uncollect person for current user
        """
        pass


if __name__ == '__main__':
    unittest.main()
