# coding: utf-8

"""
    Bangumi API

    你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 

    The version of the OpenAPI document: 2025-11-22
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.subject_book_category import SubjectBookCategory

class TestSubjectBookCategory(unittest.TestCase):
    """SubjectBookCategory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSubjectBookCategory(self):
        """Test SubjectBookCategory"""
        # inst = SubjectBookCategory()

if __name__ == '__main__':
    unittest.main()
