# coding: utf-8

"""
    Bangumi API

    你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 

    The version of the OpenAPI document: 2025-11-22
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.search_subjects_request_filter import SearchSubjectsRequestFilter

class TestSearchSubjectsRequestFilter(unittest.TestCase):
    """SearchSubjectsRequestFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchSubjectsRequestFilter:
        """Test SearchSubjectsRequestFilter
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchSubjectsRequestFilter`
        """
        model = SearchSubjectsRequestFilter()
        if include_optional:
            return SearchSubjectsRequestFilter(
                type = [
                    2
                    ],
                meta_tags = ["童年","原创"],
                tag = ["童年","原创"],
                air_date = [">=2020-07-01","<2020-10-01"],
                rating = [">=6","<8"],
                rating_count = [">=200","<5000"],
                rank = [">10","<=18"],
                nsfw = True
            )
        else:
            return SearchSubjectsRequestFilter(
        )
        """

    def testSearchSubjectsRequestFilter(self):
        """Test SearchSubjectsRequestFilter"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
