# coding: utf-8

"""
    Bangumi API

    你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 

    The version of the OpenAPI document: 2025-11-22
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.subject_revision_data import SubjectRevisionData

class TestSubjectRevisionData(unittest.TestCase):
    """SubjectRevisionData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SubjectRevisionData:
        """Test SubjectRevisionData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SubjectRevisionData`
        """
        model = SubjectRevisionData()
        if include_optional:
            return SubjectRevisionData(
                field_eps = 56,
                field_infobox = '',
                field_summary = '',
                name = '',
                name_cn = '',
                platform = 56,
                subject_id = 56,
                type = 56,
                type_id = 56,
                vote_field = ''
            )
        else:
            return SubjectRevisionData(
                field_eps = 56,
                field_infobox = '',
                field_summary = '',
                name = '',
                name_cn = '',
                platform = 56,
                subject_id = 56,
                type = 56,
                type_id = 56,
                vote_field = '',
        )
        """

    def testSubjectRevisionData(self):
        """Test SubjectRevisionData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
