# coding: utf-8

"""
    Bangumi API

    你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 

    The version of the OpenAPI document: 2025-11-22
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.blood_type import BloodType
from openapi_client.models.character_type import CharacterType
from openapi_client.models.person_images import PersonImages
from openapi_client.models.stat import Stat
from typing import Optional, Set
from typing_extensions import Self

class Character(BaseModel):
    """
    Character
    """ # noqa: E501
    id: StrictInt
    name: StrictStr
    type: CharacterType = Field(description="角色，机体，舰船，组织...")
    images: Optional[PersonImages] = Field(default=None, description="object with some size of images, this object maybe `null`")
    summary: StrictStr
    locked: StrictBool
    infobox: Optional[List[Dict[str, Any]]] = Field(default=None, description="server parsed infobox, a map from key to string or tuple null if server infobox is not valid")
    gender: Optional[StrictStr] = Field(default=None, description="parsed from wiki, maybe null")
    blood_type: Optional[BloodType] = Field(default=None, description="parsed from wiki, maybe null, `1, 2, 3, 4` for `A, B, AB, O`")
    birth_year: Optional[StrictInt] = Field(default=None, description="parsed from wiki, maybe `null`")
    birth_mon: Optional[StrictInt] = Field(default=None, description="parsed from wiki, maybe `null`")
    birth_day: Optional[StrictInt] = Field(default=None, description="parsed from wiki, maybe `null`")
    stat: Stat
    __properties: ClassVar[List[str]] = ["id", "name", "type", "images", "summary", "locked", "infobox", "gender", "blood_type", "birth_year", "birth_mon", "birth_day", "stat"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Character from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of images
        if self.images:
            _dict['images'] = self.images.to_dict()
        # override the default output from pydantic by calling `to_dict()` of stat
        if self.stat:
            _dict['stat'] = self.stat.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Character from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "type": obj.get("type"),
            "images": PersonImages.from_dict(obj["images"]) if obj.get("images") is not None else None,
            "summary": obj.get("summary"),
            "locked": obj.get("locked"),
            "infobox": obj.get("infobox"),
            "gender": obj.get("gender"),
            "blood_type": obj.get("blood_type"),
            "birth_year": obj.get("birth_year"),
            "birth_mon": obj.get("birth_mon"),
            "birth_day": obj.get("birth_day"),
            "stat": Stat.from_dict(obj["stat"]) if obj.get("stat") is not None else None
        })
        return _obj


