# coding: utf-8

"""
    Bangumi API

    你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 

    The version of the OpenAPI document: 2025-11-22
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class EpType(int, Enum):
    """
    本篇 = 0 特别篇 = 1 OP = 2 ED = 3 预告/宣传/广告 = 4 MAD = 5 其他 = 6
    """

    """
    allowed enum values
    """
    MainStory = 0
    SP = 1
    OP = 2
    ED = 3
    PV = 4
    MAD = 5
    Other = 6

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of EpType from a JSON string"""
        return cls(json.loads(json_str))


