# coding: utf-8

"""
    Bangumi API

    你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 

    The version of the OpenAPI document: 2025-11-22
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class Episode(BaseModel):
    """
    Episode
    """ # noqa: E501
    id: StrictInt
    type: StrictInt = Field(description="`0` 本篇，`1` SP，`2` OP，`3` ED")
    name: StrictStr
    name_cn: StrictStr
    sort: Union[StrictFloat, StrictInt] = Field(description="同类条目的排序和集数")
    ep: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="条目内的集数, 从`1`开始。非本篇剧集的此字段无意义")
    airdate: StrictStr
    comment: StrictInt
    duration: StrictStr = Field(description="维基人填写的原始时长")
    desc: StrictStr = Field(description="简介")
    disc: StrictInt = Field(description="音乐曲目的碟片数")
    duration_seconds: Optional[StrictInt] = Field(default=None, description="服务器解析的时长，无法解析时为 `0`")
    __properties: ClassVar[List[str]] = ["id", "type", "name", "name_cn", "sort", "ep", "airdate", "comment", "duration", "desc", "disc", "duration_seconds"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Episode from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Episode from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "type": obj.get("type"),
            "name": obj.get("name"),
            "name_cn": obj.get("name_cn"),
            "sort": obj.get("sort"),
            "ep": obj.get("ep"),
            "airdate": obj.get("airdate"),
            "comment": obj.get("comment"),
            "duration": obj.get("duration"),
            "desc": obj.get("desc"),
            "disc": obj.get("disc"),
            "duration_seconds": obj.get("duration_seconds")
        })
        return _obj


