# coding: utf-8

"""
    Bangumi API

    你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 

    The version of the OpenAPI document: 2025-11-22
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.avatar import Avatar
from openapi_client.models.user_group import UserGroup
from typing import Optional, Set
from typing_extensions import Self

class GetMyself200Response(BaseModel):
    """
    GetMyself200Response
    """ # noqa: E501
    id: StrictInt
    username: StrictStr = Field(description="唯一用户名，初始与 UID 相同，可修改一次")
    nickname: StrictStr
    user_group: UserGroup
    avatar: Avatar
    sign: StrictStr = Field(description="个人签名")
    email: Optional[StrictStr] = Field(default=None, description="用户绑定的邮箱地址")
    reg_time: Optional[datetime] = Field(default=None, description="用户注册时间。比如 2017-12-03T08:51:16+08:00")
    time_offset: Optional[StrictInt] = Field(default=None, description="用户设置的时区偏移，以小时为单位。比如 GMT+8（shanghai/beijing）为 8")
    __properties: ClassVar[List[str]] = ["id", "username", "nickname", "user_group", "avatar", "sign", "email", "reg_time", "time_offset"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetMyself200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of avatar
        if self.avatar:
            _dict['avatar'] = self.avatar.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetMyself200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "username": obj.get("username"),
            "nickname": obj.get("nickname"),
            "user_group": obj.get("user_group"),
            "avatar": Avatar.from_dict(obj["avatar"]) if obj.get("avatar") is not None else None,
            "sign": obj.get("sign"),
            "email": obj.get("email"),
            "reg_time": obj.get("reg_time"),
            "time_offset": obj.get("time_offset")
        })
        return _obj


