# coding: utf-8

"""
    Bangumi API

    你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 

    The version of the OpenAPI document: 2025-11-22
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.legacy_user import LegacyUser
from typing import Optional, Set
from typing_extensions import Self

class LegacyTopic(BaseModel):
    """
    讨论版
    """ # noqa: E501
    id: Optional[StrictInt] = Field(default=None, description="ID")
    url: Optional[StrictStr] = Field(default=None, description="地址")
    title: Optional[StrictStr] = Field(default=None, description="标题")
    main_id: Optional[StrictInt] = Field(default=None, description="所属对象（条目） ID")
    timestamp: Optional[StrictInt] = Field(default=None, description="发布时间")
    lastpost: Optional[StrictInt] = Field(default=None, description="最后回复时间")
    replies: Optional[StrictInt] = Field(default=None, description="回复数")
    user: Optional[LegacyUser] = None
    __properties: ClassVar[List[str]] = ["id", "url", "title", "main_id", "timestamp", "lastpost", "replies", "user"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LegacyTopic from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of user
        if self.user:
            _dict['user'] = self.user.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LegacyTopic from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "url": obj.get("url"),
            "title": obj.get("title"),
            "main_id": obj.get("main_id"),
            "timestamp": obj.get("timestamp"),
            "lastpost": obj.get("lastpost"),
            "replies": obj.get("replies"),
            "user": LegacyUser.from_dict(obj["user"]) if obj.get("user") is not None else None
        })
        return _obj


