# coding: utf-8

"""
    Bangumi API

    你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 

    The version of the OpenAPI document: 2025-11-22
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.legacy_subject_small_collection import LegacySubjectSmallCollection
from openapi_client.models.legacy_subject_small_images import LegacySubjectSmallImages
from openapi_client.models.legacy_subject_small_rating import LegacySubjectSmallRating
from typing import Optional, Set
from typing_extensions import Self

class LegacySubjectSmall(BaseModel):
    """
    LegacySubjectSmall
    """ # noqa: E501
    id: Optional[StrictInt] = Field(default=None, description="条目 ID")
    url: Optional[StrictStr] = Field(default=None, description="条目地址")
    type: Optional[StrictInt] = Field(default=None, description="条目类型 - `1` 为 书籍 - `2` 为 动画 - `3` 为 音乐 - `4` 为 游戏 - `6` 为 三次元  没有 `5`")
    name: Optional[StrictStr] = Field(default=None, description="条目名称")
    name_cn: Optional[StrictStr] = Field(default=None, description="条目中文名称")
    summary: Optional[StrictStr] = Field(default=None, description="剧情简介")
    air_date: Optional[StrictStr] = Field(default=None, description="放送开始日期")
    air_weekday: Optional[StrictInt] = Field(default=None, description="放送星期")
    images: Optional[LegacySubjectSmallImages] = None
    eps: Optional[StrictInt] = Field(default=None, description="话数")
    eps_count: Optional[StrictInt] = Field(default=None, description="话数")
    rating: Optional[LegacySubjectSmallRating] = None
    rank: Optional[StrictInt] = Field(default=None, description="排名")
    collection: Optional[LegacySubjectSmallCollection] = None
    __properties: ClassVar[List[str]] = ["id", "url", "type", "name", "name_cn", "summary", "air_date", "air_weekday", "images", "eps", "eps_count", "rating", "rank", "collection"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set([1, 2, 3, 4, 6]):
            raise ValueError("must be one of enum values (1, 2, 3, 4, 6)")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LegacySubjectSmall from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of images
        if self.images:
            _dict['images'] = self.images.to_dict()
        # override the default output from pydantic by calling `to_dict()` of rating
        if self.rating:
            _dict['rating'] = self.rating.to_dict()
        # override the default output from pydantic by calling `to_dict()` of collection
        if self.collection:
            _dict['collection'] = self.collection.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LegacySubjectSmall from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "url": obj.get("url"),
            "type": obj.get("type"),
            "name": obj.get("name"),
            "name_cn": obj.get("name_cn"),
            "summary": obj.get("summary"),
            "air_date": obj.get("air_date"),
            "air_weekday": obj.get("air_weekday"),
            "images": LegacySubjectSmallImages.from_dict(obj["images"]) if obj.get("images") is not None else None,
            "eps": obj.get("eps"),
            "eps_count": obj.get("eps_count"),
            "rating": LegacySubjectSmallRating.from_dict(obj["rating"]) if obj.get("rating") is not None else None,
            "rank": obj.get("rank"),
            "collection": LegacySubjectSmallCollection.from_dict(obj["collection"]) if obj.get("collection") is not None else None
        })
        return _obj


