# coding: utf-8

"""
    Bangumi API

    你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 

    The version of the OpenAPI document: 2025-11-22
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.legacy_mono_base import LegacyMonoBase
from openapi_client.models.legacy_mono_base_images import LegacyMonoBaseImages
from openapi_client.models.legacy_mono_info import LegacyMonoInfo
from typing import Optional, Set
from typing_extensions import Self

class LegacySubjectMediumAllOfCrt(BaseModel):
    """
    LegacySubjectMediumAllOfCrt
    """ # noqa: E501
    id: Optional[StrictInt] = Field(default=None, description="人物 ID")
    url: Optional[StrictStr] = Field(default=None, description="人物地址")
    name: Optional[StrictStr] = Field(default=None, description="姓名")
    images: Optional[LegacyMonoBaseImages] = None
    name_cn: Optional[StrictStr] = Field(default=None, description="简体中文名")
    comment: Optional[StrictInt] = Field(default=None, description="回复数量")
    collects: Optional[StrictInt] = Field(default=None, description="收藏人数")
    info: Optional[LegacyMonoInfo] = None
    actors: Optional[List[LegacyMonoBase]] = Field(default=None, description="声优列表")
    role_name: Optional[StrictStr] = Field(default=None, description="角色类型")
    __properties: ClassVar[List[str]] = ["id", "url", "name", "images", "name_cn", "comment", "collects", "info", "actors", "role_name"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LegacySubjectMediumAllOfCrt from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of images
        if self.images:
            _dict['images'] = self.images.to_dict()
        # override the default output from pydantic by calling `to_dict()` of info
        if self.info:
            _dict['info'] = self.info.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in actors (list)
        _items = []
        if self.actors:
            for _item_actors in self.actors:
                if _item_actors:
                    _items.append(_item_actors.to_dict())
            _dict['actors'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LegacySubjectMediumAllOfCrt from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "url": obj.get("url"),
            "name": obj.get("name"),
            "images": LegacyMonoBaseImages.from_dict(obj["images"]) if obj.get("images") is not None else None,
            "name_cn": obj.get("name_cn"),
            "comment": obj.get("comment"),
            "collects": obj.get("collects"),
            "info": LegacyMonoInfo.from_dict(obj["info"]) if obj.get("info") is not None else None,
            "actors": [LegacyMonoBase.from_dict(_item) for _item in obj["actors"]] if obj.get("actors") is not None else None,
            "role_name": obj.get("role_name")
        })
        return _obj


