# coding: utf-8

"""
    Bangumi API

    你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 

    The version of the OpenAPI document: 2025-11-22
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.legacy_episode_type import LegacyEpisodeType
from typing import Optional, Set
from typing_extensions import Self

class LegacyEpisode(BaseModel):
    """
    章节信息
    """ # noqa: E501
    id: Optional[StrictInt] = Field(default=None, description="章节 ID")
    url: Optional[StrictStr] = Field(default=None, description="章节地址")
    type: Optional[LegacyEpisodeType] = None
    sort: Optional[StrictInt] = Field(default=None, description="集数")
    name: Optional[StrictStr] = Field(default=None, description="标题")
    name_cn: Optional[StrictStr] = Field(default=None, description="简体中文标题")
    duration: Optional[StrictStr] = Field(default=None, description="时长")
    airdate: Optional[StrictStr] = Field(default=None, description="放送日期")
    comment: Optional[StrictInt] = Field(default=None, description="回复数量")
    desc: Optional[StrictStr] = Field(default=None, description="简介")
    status: Optional[StrictStr] = Field(default=None, description="放送状态 <br> Air = 已放送 <br> Today = 正在放送 <br> NA = 未放送")
    __properties: ClassVar[List[str]] = ["id", "url", "type", "sort", "name", "name_cn", "duration", "airdate", "comment", "desc", "status"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Air', 'Today', 'NA']):
            raise ValueError("must be one of enum values ('Air', 'Today', 'NA')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LegacyEpisode from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LegacyEpisode from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "url": obj.get("url"),
            "type": obj.get("type"),
            "sort": obj.get("sort"),
            "name": obj.get("name"),
            "name_cn": obj.get("name_cn"),
            "duration": obj.get("duration"),
            "airdate": obj.get("airdate"),
            "comment": obj.get("comment"),
            "desc": obj.get("desc"),
            "status": obj.get("status")
        })
        return _obj


