# coding: utf-8

"""
    Bangumi API

    你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 

    The version of the OpenAPI document: 2025-11-22
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.legacy_mono_info_alias import LegacyMonoInfoAlias
from openapi_client.models.legacy_mono_info_source import LegacyMonoInfoSource
from typing import Optional, Set
from typing_extensions import Self

class LegacyMonoInfo(BaseModel):
    """
    人物信息
    """ # noqa: E501
    birth: Optional[StrictStr] = Field(default=None, description="生日")
    height: Optional[StrictStr] = Field(default=None, description="身高")
    gender: Optional[StrictStr] = Field(default=None, description="性别")
    alias: Optional[LegacyMonoInfoAlias] = None
    source: Optional[LegacyMonoInfoSource] = None
    name_cn: Optional[StrictStr] = Field(default=None, description="简体中文名")
    cv: Optional[StrictStr] = Field(default=None, description="声优")
    __properties: ClassVar[List[str]] = ["birth", "height", "gender", "alias", "source", "name_cn", "cv"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LegacyMonoInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of alias
        if self.alias:
            _dict['alias'] = self.alias.to_dict()
        # override the default output from pydantic by calling `to_dict()` of source
        if self.source:
            _dict['source'] = self.source.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LegacyMonoInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "birth": obj.get("birth"),
            "height": obj.get("height"),
            "gender": obj.get("gender"),
            "alias": LegacyMonoInfoAlias.from_dict(obj["alias"]) if obj.get("alias") is not None else None,
            "source": LegacyMonoInfoSource.from_dict(obj["source"]) if obj.get("source") is not None else None,
            "name_cn": obj.get("name_cn"),
            "cv": obj.get("cv")
        })
        return _obj


