# coding: utf-8

"""
    Bangumi API

    你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 

    The version of the OpenAPI document: 2025-11-22
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.search_subjects_request_filter import SearchSubjectsRequestFilter
from typing import Optional, Set
from typing_extensions import Self

from openapi_client.models.collection import Collection
from openapi_client.models.images import Images
from openapi_client.models.item import Item
from openapi_client.models.rating import Rating
from openapi_client.models.subject_type import SubjectType
from openapi_client.models.tag import Tag

class SearchSubjectsRequest(BaseModel):
    """
    SearchSubjectsRequest
    """ # noqa: E501
    keyword: StrictStr
    sort: Optional[StrictStr] = Field(default='match', description="排序规则  - `match` meilisearch 的默认排序，按照匹配程度 - `heat` 收藏人数 - `rank` 排名由高到低 - `score` 评分 ")
    filter: Optional[SearchSubjectsRequestFilter] = None
    __properties: ClassVar[List[str]] = ["keyword", "sort", "filter"]

    @field_validator('sort')
    def sort_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['match', 'heat', 'rank', 'score']):
            raise ValueError("must be one of enum values ('match', 'heat', 'rank', 'score')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SearchSubjectsRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of filter
        if self.filter:
            _dict['filter'] = self.filter.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SearchSubjectsRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "keyword": obj.get("keyword"),
            "sort": obj.get("sort") if obj.get("sort") is not None else 'match',
            "filter": SearchSubjectsRequestFilter.from_dict(obj["filter"]) if obj.get("filter") is not None else None
        })
        return _obj

class SearchSubject(BaseModel):
    """
    SearchSubject
    """
    id: StrictInt
    type: SubjectType
    name: StrictStr
    name_cn: StrictStr
    summary: StrictStr
    series: StrictBool = Field(description="是否为书籍系列的主条目")
    nsfw: StrictBool
    locked: StrictBool
    var_date: Optional[StrictStr] = Field(default=None, description="air date in `YYYY-MM-DD` format", alias="date")
    platform: StrictStr = Field(description="TV, Web, 欧美剧, DLC...")
    image: StrictStr
    infobox: Optional[List[Item]] = None
    volumes: StrictInt = Field(description="书籍条目的册数，由旧服务端从wiki中解析")
    eps: StrictInt = Field(description="由旧服务端从wiki中解析，对于书籍条目为`话数`")
    # total_episodes: StrictInt = Field(description="数据库中的章节数量")
    # rating: Rating
    # collection: Collection
    # meta_tags: List[StrictStr] = Field(description="由维基人维护的 tag")
    tags: List[Tag]
    __properties: ClassVar[List[str]] = ["id", "type", "name", "name_cn", "summary", "series", "nsfw", "locked", "date", "platform", "image", "infobox", "volumes", "eps", "tags"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Subject from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        
        # override the default output from pydantic by calling `to_dict()` of each item in infobox (list)
        _items = []
        if self.infobox:
            for _item_infobox in self.infobox:
                if _item_infobox:
                    _items.append(_item_infobox.to_dict())
            _dict['infobox'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in tags (list)
        _items = []
        if self.tags:
            for _item_tags in self.tags:
                if _item_tags:
                    _items.append(_item_tags.to_dict())
            _dict['tags'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Subject from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "type": obj.get("type"),
            "name": obj.get("name"),
            "name_cn": obj.get("name_cn"),
            "summary": obj.get("summary"),
            "series": obj.get("series"),
            "nsfw": obj.get("nsfw"),
            "locked": obj.get("locked"),
            "date": obj.get("date"),
            "platform": obj.get("platform"),
            "image": obj.get("image"),
            "infobox": [Item.from_dict(_item) for _item in obj["infobox"]] if obj.get("infobox") is not None else None,
            "volumes": obj.get("volumes"),
            "eps": obj.get("eps"),
            "tags": [Tag.from_dict(_item) for _item in obj["tags"]] if obj.get("tags") is not None else None
        })
        return _obj

