# coding: utf-8

"""
    Bangumi API

    你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 

    The version of the OpenAPI document: 2025-11-22
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class SubjectCategory(int, Enum):
    """
    SubjectCategory
    """

    """
    allowed enum values
    """
    NUMBER_0 = 0
    NUMBER_1001 = 1001
    NUMBER_1002 = 1002
    NUMBER_1003 = 1003
    NUMBER_1 = 1
    NUMBER_2 = 2
    NUMBER_3 = 3
    NUMBER_5 = 5
    NUMBER_4001 = 4001
    NUMBER_4003 = 4003
    NUMBER_4002 = 4002
    NUMBER_4005 = 4005
    NUMBER_6001 = 6001
    NUMBER_6002 = 6002
    NUMBER_6003 = 6003
    NUMBER_6004 = 6004

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SubjectCategory from a JSON string"""
        return cls(json.loads(json_str))


