# coding: utf-8

"""
    Bangumi API

    你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 

    The version of the OpenAPI document: 2025-11-22
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class SubjectCollectionType(int, Enum):
    """
    - `1`: 想看 - `2`: 看过 - `3`: 在看 - `4`: 搁置 - `5`: 抛弃
    """

    """
    allowed enum values
    """
    Wish = 1
    Done = 2
    Doing = 3
    OnHold = 4
    Dropped = 5

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SubjectCollectionType from a JSON string"""
        return cls(json.loads(json_str))


