# coding: utf-8

"""
    Bangumi API

    你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 

    The version of the OpenAPI document: 2025-11-22
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class SubjectBookCategory(int, Enum):
    """
    书籍类型 - `0` 为 其他 - `1001` 为 漫画 - `1002` 为 小说 - `1003` 为 画集
    """

    """
    allowed enum values
    """
    Other = 0
    Comic = 1001
    Novel = 1002
    Illustration = 1003

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SubjectBookCategory from a JSON string"""
        return cls(json.loads(json_str))


