# coding: utf-8

"""
    Bangumi API

    你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 

    The version of the OpenAPI document: 2025-11-22
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from openapi_client.models.subject_collection_type import SubjectCollectionType
from typing import Optional, Set
from typing_extensions import Self

class UserSubjectCollectionModifyPayload(BaseModel):
    """
    所有的字段均可选
    """ # noqa: E501
    type: Optional[SubjectCollectionType] = Field(default=None, description="修改条目收藏类型")
    rate: Optional[Annotated[int, Field(le=10, strict=True, ge=0)]] = Field(default=None, description="评分，`0` 表示删除评分")
    ep_status: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="只能用于修改书籍条目进度")
    vol_status: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="只能用于修改书籍条目进度")
    comment: Optional[StrictStr] = Field(default=None, description="评价")
    private: Optional[StrictBool] = Field(default=None, description="仅自己可见")
    tags: Optional[List[StrictStr]] = Field(default=None, description="不传或者 `null` 都会被忽略，传 `[]` 则会删除所有 tag。")
    __properties: ClassVar[List[str]] = ["type", "rate", "ep_status", "vol_status", "comment", "private", "tags"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UserSubjectCollectionModifyPayload from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UserSubjectCollectionModifyPayload from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "rate": obj.get("rate"),
            "ep_status": obj.get("ep_status"),
            "vol_status": obj.get("vol_status"),
            "comment": obj.get("comment"),
            "private": obj.get("private"),
            "tags": obj.get("tags")
        })
        return _obj


