# coding: utf-8

"""
    Bangumi API

    你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 

    The version of the OpenAPI document: 2025-11-22
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.slim_subject import SlimSubject
from openapi_client.models.subject_collection_type import SubjectCollectionType
from openapi_client.models.subject_type import SubjectType
from typing import Optional, Set
from typing_extensions import Self

class UserSubjectCollection(BaseModel):
    """
    UserSubjectCollection
    """ # noqa: E501
    subject_id: StrictInt
    subject_type: SubjectType
    rate: StrictInt
    type: SubjectCollectionType
    comment: Optional[StrictStr] = None
    tags: List[StrictStr]
    ep_status: StrictInt
    vol_status: StrictInt
    updated_at: datetime = Field(description="本时间并不代表条目的收藏时间。修改评分，评价，章节观看状态等收藏信息时未更新此时间是一个 bug。请不要依赖此特性")
    private: StrictBool
    subject: Optional[SlimSubject] = None
    __properties: ClassVar[List[str]] = ["subject_id", "subject_type", "rate", "type", "comment", "tags", "ep_status", "vol_status", "updated_at", "private", "subject"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UserSubjectCollection from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of subject
        if self.subject:
            _dict['subject'] = self.subject.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UserSubjectCollection from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "subject_id": obj.get("subject_id"),
            "subject_type": obj.get("subject_type"),
            "rate": obj.get("rate"),
            "type": obj.get("type"),
            "comment": obj.get("comment"),
            "tags": obj.get("tags"),
            "ep_status": obj.get("ep_status"),
            "vol_status": obj.get("vol_status"),
            "updated_at": obj.get("updated_at"),
            "private": obj.get("private"),
            "subject": SlimSubject.from_dict(obj["subject"]) if obj.get("subject") is not None else None
        })
        return _obj


