# coding: utf-8

"""
    Bangumi API

    你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 

    The version of the OpenAPI document: 2025-11-22
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class UserGroup(int, Enum):
    """
    用户组 - 1 = 管理员 - 2 = Bangumi 管理猿 - 3 = 天窗管理猿 - 4 = 禁言用户 - 5 = 禁止访问用户 - 8 = 人物管理猿 - 9 = 维基条目管理猿 - 10 = 用户 - 11 = 维基人
    """

    """
    allowed enum values
    """
    Admin = 1
    BangumiAdmin = 2
    DoujinAdmin = 3
    MutedUser = 4
    BlockedUser = 5
    PersonAdmin = 8
    WikiAdmin = 9
    User = 10
    WikiUser = 11

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of UserGroup from a JSON string"""
        return cls(json.loads(json_str))


