# coding: utf-8

# flake8: noqa

"""
    Bangumi API

    你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 

    The version of the OpenAPI document: 2025-11-22
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "DefaultApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "Avatar",
    "BloodType",
    "Character",
    "CharacterPerson",
    "CharacterRevision",
    "CharacterRevisionDataItem",
    "CharacterType",
    "Collection",
    "Count",
    "Creator",
    "Detail",
    "DetailOneOf",
    "DetailedRevision",
    "EpType",
    "Episode",
    "EpisodeCollectionType",
    "EpisodeDetail",
    "ErrorDetail",
    "GetCalendar200ResponseInner",
    "GetCalendar200ResponseInnerWeekday",
    "GetMyself200Response",
    "GetUserSubjectEpisodeCollection200Response",
    "Images",
    "Index",
    "IndexBasicInfo",
    "IndexSubject",
    "IndexSubjectAddInfo",
    "IndexSubjectEditInfo",
    "Item",
    "KV",
    "LegacyBlog",
    "LegacyCharacter",
    "LegacyEpisode",
    "LegacyEpisodeType",
    "LegacyMono",
    "LegacyMonoBase",
    "LegacyMonoBaseImages",
    "LegacyMonoInfo",
    "LegacyMonoInfoAlias",
    "LegacyMonoInfoSource",
    "LegacyPerson",
    "LegacySubjectLarge",
    "LegacySubjectMedium",
    "LegacySubjectMediumAllOfCrt",
    "LegacySubjectMediumAllOfStaff",
    "LegacySubjectSmall",
    "LegacySubjectSmallCollection",
    "LegacySubjectSmallImages",
    "LegacySubjectSmallRating",
    "LegacySubjectSmallRatingCount",
    "LegacySubjectType",
    "LegacyTopic",
    "LegacyUser",
    "LegacyUserAvatar",
    "LegacyUserGroup",
    "Page",
    "PagedCharacter",
    "PagedEpisode",
    "PagedIndexSubject",
    "PagedPerson",
    "PagedRevision",
    "PagedSubject",
    "PagedUserCharacterCollection",
    "PagedUserCollection",
    "PagedUserPersonCollection",
    "PatchUserSubjectEpisodeCollectionRequest",
    "Person",
    "PersonCareer",
    "PersonCharacter",
    "PersonDetail",
    "PersonImages",
    "PersonRevision",
    "PersonRevisionDataItem",
    "PersonRevisionProfession",
    "PersonType",
    "PutUserEpisodeCollectionRequest",
    "Rating",
    "RelatedCharacter",
    "RelatedPerson",
    "Revision",
    "RevisionExtra",
    "SearchCharactersRequest",
    "SearchCharactersRequestFilter",
    "SearchPersonsRequest",
    "SearchPersonsRequestFilter",
    "SearchSubjectsRequest",
    "SearchSubjectsRequestFilter",
    "SlimSubject",
    "Stat",
    "Subject",
    "SubjectAnimeCategory",
    "SubjectBookCategory",
    "SubjectCategory",
    "SubjectCollectionType",
    "SubjectGameCategory",
    "SubjectRealCategory",
    "SubjectRevision",
    "SubjectRevisionData",
    "SubjectType",
    "Tag",
    "User",
    "UserCharacterCollection",
    "UserEpisodeCollection",
    "UserGroup",
    "UserPersonCollection",
    "UserSubjectCollection",
    "UserSubjectCollectionModifyPayload",
    "V",
    "V0RelatedSubject",
    "V0SubjectRelation",
    "Value",
    "ValueAnyOfInner",
]

# import apis into sdk package
from openapi_client.api.default_api import DefaultApi as DefaultApi

# import ApiClient
from openapi_client.api_response import ApiResponse as ApiResponse
from openapi_client.api_client import ApiClient as ApiClient
from openapi_client.configuration import Configuration as Configuration
from openapi_client.exceptions import OpenApiException as OpenApiException
from openapi_client.exceptions import ApiTypeError as ApiTypeError
from openapi_client.exceptions import ApiValueError as ApiValueError
from openapi_client.exceptions import ApiKeyError as ApiKeyError
from openapi_client.exceptions import ApiAttributeError as ApiAttributeError
from openapi_client.exceptions import ApiException as ApiException

# import models into sdk package
from openapi_client.models.avatar import Avatar as Avatar
from openapi_client.models.blood_type import BloodType as BloodType
from openapi_client.models.character import Character as Character
from openapi_client.models.character_person import CharacterPerson as CharacterPerson
from openapi_client.models.character_revision import CharacterRevision as CharacterRevision
from openapi_client.models.character_revision_data_item import CharacterRevisionDataItem as CharacterRevisionDataItem
from openapi_client.models.character_type import CharacterType as CharacterType
from openapi_client.models.collection import Collection as Collection
from openapi_client.models.count import Count as Count
from openapi_client.models.creator import Creator as Creator
from openapi_client.models.detail import Detail as Detail
from openapi_client.models.detail_one_of import DetailOneOf as DetailOneOf
from openapi_client.models.detailed_revision import DetailedRevision as DetailedRevision
from openapi_client.models.ep_type import EpType as EpType
from openapi_client.models.episode import Episode as Episode
from openapi_client.models.episode_collection_type import EpisodeCollectionType as EpisodeCollectionType
from openapi_client.models.episode_detail import EpisodeDetail as EpisodeDetail
from openapi_client.models.error_detail import ErrorDetail as ErrorDetail
from openapi_client.models.get_calendar200_response_inner import GetCalendar200ResponseInner as GetCalendar200ResponseInner
from openapi_client.models.get_calendar200_response_inner_weekday import GetCalendar200ResponseInnerWeekday as GetCalendar200ResponseInnerWeekday
from openapi_client.models.get_myself200_response import GetMyself200Response as GetMyself200Response
from openapi_client.models.get_user_subject_episode_collection200_response import GetUserSubjectEpisodeCollection200Response as GetUserSubjectEpisodeCollection200Response
from openapi_client.models.images import Images as Images
from openapi_client.models.index import Index as Index
from openapi_client.models.index_basic_info import IndexBasicInfo as IndexBasicInfo
from openapi_client.models.index_subject import IndexSubject as IndexSubject
from openapi_client.models.index_subject_add_info import IndexSubjectAddInfo as IndexSubjectAddInfo
from openapi_client.models.index_subject_edit_info import IndexSubjectEditInfo as IndexSubjectEditInfo
from openapi_client.models.item import Item as Item
from openapi_client.models.kv import KV as KV
from openapi_client.models.legacy_blog import LegacyBlog as LegacyBlog
from openapi_client.models.legacy_character import LegacyCharacter as LegacyCharacter
from openapi_client.models.legacy_episode import LegacyEpisode as LegacyEpisode
from openapi_client.models.legacy_episode_type import LegacyEpisodeType as LegacyEpisodeType
from openapi_client.models.legacy_mono import LegacyMono as LegacyMono
from openapi_client.models.legacy_mono_base import LegacyMonoBase as LegacyMonoBase
from openapi_client.models.legacy_mono_base_images import LegacyMonoBaseImages as LegacyMonoBaseImages
from openapi_client.models.legacy_mono_info import LegacyMonoInfo as LegacyMonoInfo
from openapi_client.models.legacy_mono_info_alias import LegacyMonoInfoAlias as LegacyMonoInfoAlias
from openapi_client.models.legacy_mono_info_source import LegacyMonoInfoSource as LegacyMonoInfoSource
from openapi_client.models.legacy_person import LegacyPerson as LegacyPerson
from openapi_client.models.legacy_subject_large import LegacySubjectLarge as LegacySubjectLarge
from openapi_client.models.legacy_subject_medium import LegacySubjectMedium as LegacySubjectMedium
from openapi_client.models.legacy_subject_medium_all_of_crt import LegacySubjectMediumAllOfCrt as LegacySubjectMediumAllOfCrt
from openapi_client.models.legacy_subject_medium_all_of_staff import LegacySubjectMediumAllOfStaff as LegacySubjectMediumAllOfStaff
from openapi_client.models.legacy_subject_small import LegacySubjectSmall as LegacySubjectSmall
from openapi_client.models.legacy_subject_small_collection import LegacySubjectSmallCollection as LegacySubjectSmallCollection
from openapi_client.models.legacy_subject_small_images import LegacySubjectSmallImages as LegacySubjectSmallImages
from openapi_client.models.legacy_subject_small_rating import LegacySubjectSmallRating as LegacySubjectSmallRating
from openapi_client.models.legacy_subject_small_rating_count import LegacySubjectSmallRatingCount as LegacySubjectSmallRatingCount
from openapi_client.models.legacy_subject_type import LegacySubjectType as LegacySubjectType
from openapi_client.models.legacy_topic import LegacyTopic as LegacyTopic
from openapi_client.models.legacy_user import LegacyUser as LegacyUser
from openapi_client.models.legacy_user_avatar import LegacyUserAvatar as LegacyUserAvatar
from openapi_client.models.legacy_user_group import LegacyUserGroup as LegacyUserGroup
from openapi_client.models.page import Page as Page
from openapi_client.models.paged_character import PagedCharacter as PagedCharacter
from openapi_client.models.paged_episode import PagedEpisode as PagedEpisode
from openapi_client.models.paged_index_subject import PagedIndexSubject as PagedIndexSubject
from openapi_client.models.paged_person import PagedPerson as PagedPerson
from openapi_client.models.paged_revision import PagedRevision as PagedRevision
from openapi_client.models.paged_subject import PagedSubject as PagedSubject
from openapi_client.models.paged_user_character_collection import PagedUserCharacterCollection as PagedUserCharacterCollection
from openapi_client.models.paged_user_collection import PagedUserCollection as PagedUserCollection
from openapi_client.models.paged_user_person_collection import PagedUserPersonCollection as PagedUserPersonCollection
from openapi_client.models.patch_user_subject_episode_collection_request import PatchUserSubjectEpisodeCollectionRequest as PatchUserSubjectEpisodeCollectionRequest
from openapi_client.models.person import Person as Person
from openapi_client.models.person_career import PersonCareer as PersonCareer
from openapi_client.models.person_character import PersonCharacter as PersonCharacter
from openapi_client.models.person_detail import PersonDetail as PersonDetail
from openapi_client.models.person_images import PersonImages as PersonImages
from openapi_client.models.person_revision import PersonRevision as PersonRevision
from openapi_client.models.person_revision_data_item import PersonRevisionDataItem as PersonRevisionDataItem
from openapi_client.models.person_revision_profession import PersonRevisionProfession as PersonRevisionProfession
from openapi_client.models.person_type import PersonType as PersonType
from openapi_client.models.put_user_episode_collection_request import PutUserEpisodeCollectionRequest as PutUserEpisodeCollectionRequest
from openapi_client.models.rating import Rating as Rating
from openapi_client.models.related_character import RelatedCharacter as RelatedCharacter
from openapi_client.models.related_person import RelatedPerson as RelatedPerson
from openapi_client.models.revision import Revision as Revision
from openapi_client.models.revision_extra import RevisionExtra as RevisionExtra
from openapi_client.models.search_characters_request import SearchCharactersRequest as SearchCharactersRequest
from openapi_client.models.search_characters_request_filter import SearchCharactersRequestFilter as SearchCharactersRequestFilter
from openapi_client.models.search_persons_request import SearchPersonsRequest as SearchPersonsRequest
from openapi_client.models.search_persons_request_filter import SearchPersonsRequestFilter as SearchPersonsRequestFilter
from openapi_client.models.search_subjects_request import SearchSubjectsRequest as SearchSubjectsRequest
from openapi_client.models.search_subjects_request_filter import SearchSubjectsRequestFilter as SearchSubjectsRequestFilter
from openapi_client.models.slim_subject import SlimSubject as SlimSubject
from openapi_client.models.stat import Stat as Stat
from openapi_client.models.subject import Subject as Subject
from openapi_client.models.subject_anime_category import SubjectAnimeCategory as SubjectAnimeCategory
from openapi_client.models.subject_book_category import SubjectBookCategory as SubjectBookCategory
from openapi_client.models.subject_category import SubjectCategory as SubjectCategory
from openapi_client.models.subject_collection_type import SubjectCollectionType as SubjectCollectionType
from openapi_client.models.subject_game_category import SubjectGameCategory as SubjectGameCategory
from openapi_client.models.subject_real_category import SubjectRealCategory as SubjectRealCategory
from openapi_client.models.subject_revision import SubjectRevision as SubjectRevision
from openapi_client.models.subject_revision_data import SubjectRevisionData as SubjectRevisionData
from openapi_client.models.subject_type import SubjectType as SubjectType
from openapi_client.models.tag import Tag as Tag
from openapi_client.models.user import User as User
from openapi_client.models.user_character_collection import UserCharacterCollection as UserCharacterCollection
from openapi_client.models.user_episode_collection import UserEpisodeCollection as UserEpisodeCollection
from openapi_client.models.user_group import UserGroup as UserGroup
from openapi_client.models.user_person_collection import UserPersonCollection as UserPersonCollection
from openapi_client.models.user_subject_collection import UserSubjectCollection as UserSubjectCollection
from openapi_client.models.user_subject_collection_modify_payload import UserSubjectCollectionModifyPayload as UserSubjectCollectionModifyPayload
from openapi_client.models.v import V as V
from openapi_client.models.v0_related_subject import V0RelatedSubject as V0RelatedSubject
from openapi_client.models.v0_subject_relation import V0SubjectRelation as V0SubjectRelation
from openapi_client.models.value import Value as Value
from openapi_client.models.value_any_of_inner import ValueAnyOfInner as ValueAnyOfInner

